from setuptools import setup, find_packages

setup(name='gym_cooking',
      version='0.0.1',
      description='Too Many Cooks: Overcooked environment',
      author='Rose E. Wang',
      email='rewang@stanford.edu',
      packages=find_packages(),
      install_requires=[
            'cloudpickle',
            'decorator',
            'dill',
            'future',
            'gym==0.21',
            'matplotlib',
            'networkx',
            'numpy',
            'pandas',
            'Pillow',
            'pygame',
            'pyglet',
            'pyparsing',
            'python-dateutil',
            'pytz',
            'scipy',
            'seaborn',
            'six',
            'termcolor',
            'tqdm',
          ]
      )
